test_startup;

%% processing parameters
sim = simulator.SimulatorConvexRoom();  % simulator object

set(sim, ...
  'BlockSize', 4096, ...
  'SampleRate', 44100, ...
  'Renderer', @ssr_brs ...
  );

% acoustic scene
set(sim, ...
  'Sources', {simulator.source.Point(), simulator.source.Point()}, ...
  'Sinks', simulator.AudioSink(2) ...
  );

% set parameters of audio sources
set(sim.Sources{1}, ...
  'AudioBuffer', simulator.buffer.FIFO(1), ...
  'Position', [1; 2; 1.75], ...
  'Name', 'Cello', ...
  'Volume', 0.4, ...
  'IRDataset', simulator.DirectionalIR('TWOEARS_KEMAR_ADREAMS_pos1.sofa', 1), ...
  'Mute', true ...
  );

set(sim.Sources{2}, ...
  'AudioBuffer', simulator.buffer.FIFO(1), ...
  'Position', [1; -2; 1.75], ...
  'Name', 'Castanets', ...
  'IRDataset', simulator.DirectionalIR('TWOEARS_KEMAR_ADREAMS_pos1.sofa', 2) ...
  );

% set audio input of buffers
set(sim.Sources{1}.AudioBuffer, ...
  'File', 'stimuli/anechoic/instruments/anechoic_cello.wav');
set(sim.Sources{2}.AudioBuffer, ...
  'File', 'stimuli/anechoic/instruments/anechoic_castanets.wav');

% set parameters of head
set(sim.Sinks, ...
  'Position' , [0; 0; 0], ...
  'Name', 'Head' ...
  );

%% initialization
% note that all the parameters including objects' positions have to be
% defined BEFORE initialization in order to init properly
sim.set('Init',true);

%% dynamic scene

sim.rotateHead(-27.7541, 'absolute');
sim.Sinks.setDynamic('UnitX', 'Velocity', 30);
sim.rotateHead(176.2459, 'absolute');

while ~sim.isFinished()
  sim.set('Refresh',true);  % refresh all objects
  sim.set('Process',true);
end

sim.plot();

% save file
sim.Sinks.saveFile('out_multispeaker.wav',sim.SampleRate);
%% clean up
sim.set('ShutDown',true);
