test_startup;

%% processing parameters
sim = simulator.SimulatorConvexRoom();  % simulator object

set(sim, ...
  'BlockSize', 4096, ...
  'SampleRate', 44100, ...
  'MaximumDelay', 0.05, ...
  'PreDelay', 0.0, ...
  'LengthOfSimulation', 5.0, ...
  'Renderer', @ssr_binaural, ...
  'HRIRDataset', simulator.DirectionalIR( ...
    'impulse_responses/qu_kemar_anechoic/QU_KEMAR_anechoic_3m.sofa') ...
  );

% acoustic scene
set(sim, ...
  'Sources', {simulator.source.Point(), simulator.source.Point()}, ...
  'Sinks', simulator.AudioSink(2) ...
  );

% set parameters of audio sources
set(sim.Sources{1}, ...
  'AudioBuffer', simulator.buffer.FIFO(1), ...
  'Position', [1; 2; 1.75], ...
  'Name', 'Cello', ...
  'Volume', 0.4 ...
  );

set(sim.Sources{2}, ...
  'AudioBuffer', simulator.buffer.FIFO(1), ...
  'Position', [1; -2; 1.75], ...
  'Name', 'Castanets' ...
  );

% set audio input of buffers
set(sim.Sources{1}.AudioBuffer, ...
  'File', 'stimuli/anechoic/instruments/anechoic_cello.wav');
set(sim.Sources{2}.AudioBuffer, ...
  'File', 'stimuli/anechoic/instruments/anechoic_castanets.wav');

% set parameters of head
set(sim.Sinks, ...
  'Position' , [0; 0; 1.75], ...
  'UnitFront', [1; 0; 0], ...
  'UnitUp', [0; 0; 1], ...
  'Name', 'Head' ...
  );

%% initialization
% note that all the parameters including objects' positions have to be
% defined BEFORE initialization in order to init properly
sim.set('Init',true);

%% dynamic scene

% move first source with 0.25 meters per seconds
sim.Sources{1}.setDynamic('Position', 'Velocity', 0.25);
sim.Sources{1}.set('Position', [1; -2; 1.75]);

while ~sim.isFinished()
  sim.set('Refresh',true);  % refresh all objects
  sim.set('Process',true);
end

sim.plot();

% save file
sim.Sinks.saveFile('out_binaural_wo.wav',sim.SampleRate);
%% clean up
sim.set('ShutDown',true);
