#!/bin/sh

# Create Doxygen documentation and push to git server.

# Prepare your working copy for pushing the documentation to Github:
#
# cd doc
# git clone https://user@github.com/twoears/twoears-binaural-simulator-doc html

set -e

VERSION=$(git describe --always)
BRANCH=$(git symbolic-ref --short HEAD)

if [ -d html ]
then
  cd html
  if [ -d .git ]
  then
    git rm -rf --ignore-unmatch .
  fi
  cd ..
fi

matlab -nojvm -nosplash -r createdoc
# copy xml schema to html output directory
cp ../../src/+xml/tef.xsd ./html/
cp ../../src/+xml/tef.xsl ./html/

cd html

if [ -d .git ]
then
  echo -n "Push to Github? [yN] "
  read ANSWER
  if [ "$ANSWER" = Y -o "$ANSWER" = y ]
  then
    git add . \
&& git rm --ignore-unmatch ./*~  \
&& git commit -m "Doxygen documentation for $VERSION" \
&& git push --force
  else
    xdg-open index.html
  fi
fi
