function nodbfound()
    warning([
      'It seems, that the Two!Ears database is not included ', ...
      'correctly. This may be a path issue. If you ', ...
      'have not yet downloaded the Two!Ears, get it from', ...
      'https://dev.qu.tu-berlin.de/git/twoears-data via git' ...
      ]);
end